/**
 * MindOS Care Plans Domain Types & Taxonomies
 * Authority: Master Architecture Index Section 7 & 14, Volumes I, III, XV & Appendices B / C / Q
 * Sprint 22 Bounded Context
 */

import {
  CarePlanState,
  CareGoalStatus
} from '../../platform/shared/state_machines.js';

export {
  CarePlanState,
  CareGoalStatus
};

export enum CarePlanType {
  SHORT_TERM_SUPPORT = 'SHORT_TERM_SUPPORT',
  COUNSELLING = 'COUNSELLING',
  PSYCHOLOGICAL_SUPPORT = 'PSYCHOLOGICAL_SUPPORT',
  PSYCHIATRIC_SUPPORT = 'PSYCHIATRIC_SUPPORT',
  CARE_COORDINATION = 'CARE_COORDINATION',
  RECOVERY_SUPPORT = 'RECOVERY_SUPPORT',
  FOLLOW_UP = 'FOLLOW_UP',
  OTHER_APPROVED = 'OTHER_APPROVED'
}

export enum CarePlanVersionStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  SUPERSEDED = 'SUPERSEDED',
  REVOKED = 'REVOKED'
}

export enum CareGoalType {
  SYMPTOM_MANAGEMENT = 'SYMPTOM_MANAGEMENT',
  FUNCTIONING = 'FUNCTIONING',
  COPING = 'COPING',
  SLEEP = 'SLEEP',
  CARE_ENGAGEMENT = 'CARE_ENGAGEMENT',
  SAFETY = 'SAFETY',
  WELLBEING = 'WELLBEING',
  SOCIAL_SUPPORT = 'SOCIAL_SUPPORT',
  BEHAVIORAL = 'BEHAVIORAL',
  RECOVERY = 'RECOVERY',
  OTHER_APPROVED = 'OTHER_APPROVED'
}

export enum CareGoalProvenance {
  USER_SELECTED = 'USER_SELECTED',
  COLLABORATIVE = 'COLLABORATIVE',
  PROFESSIONAL_RECOMMENDED = 'PROFESSIONAL_RECOMMENDED',
  SYSTEM_SUGGESTED = 'SYSTEM_SUGGESTED',
  AI_SUGGESTED = 'AI_SUGGESTED'
}

export enum GoalPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum GoalTargetType {
  ASSESSMENT_SCORE = 'ASSESSMENT_SCORE',
  TASK_COMPLETION = 'TASK_COMPLETION',
  USER_RATING = 'USER_RATING',
  CLINICAL_EVALUATION = 'CLINICAL_EVALUATION',
  BEHAVIORAL_FREQUENCY = 'BEHAVIORAL_FREQUENCY'
}

export enum CareInterventionType {
  CONTENT = 'CONTENT',
  GUIDED_EXERCISE = 'GUIDED_EXERCISE',
  ASSESSMENT = 'ASSESSMENT',
  PROFESSIONAL_SESSION = 'PROFESSIONAL_SESSION',
  SELF_MONITORING = 'SELF_MONITORING',
  CARE_COORDINATION = 'CARE_COORDINATION',
  FOLLOW_UP = 'FOLLOW_UP',
  SAFETY_PLAN = 'SAFETY_PLAN',
  OTHER_GOVERNED = 'OTHER_GOVERNED'
}

export enum CarePlanReviewType {
  SCHEDULED = 'SCHEDULED',
  MILESTONE = 'MILESTONE',
  SAFETY_TRIGGERED = 'SAFETY_TRIGGERED',
  ASSESSMENT_TRIGGERED = 'ASSESSMENT_TRIGGERED',
  PROFESSIONAL_REQUESTED = 'PROFESSIONAL_REQUESTED',
  USER_REQUESTED = 'USER_REQUESTED',
  TRANSFER = 'TRANSFER'
}

export enum CarePlanReviewOutcome {
  CONTINUE = 'CONTINUE',
  MODIFY = 'MODIFY',
  PAUSE = 'PAUSE',
  COMPLETE = 'COMPLETE',
  TERMINATE = 'TERMINATE',
  ESCALATE = 'ESCALATE'
}

export enum CarePlanEligibilityStatus {
  ELIGIBLE = 'ELIGIBLE',
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW'
}
